CUDA_VISIBLE_DEVICES=0 python3 run_pretrain.py
--task viznet
--dataset Datasets
--batch_size 64
--lr 5e-5
--lm roberta
--n_epochs 3
--max_len 128
--size 10000
--projector 768
--save_model
--augment_op drop_col
--sample_meth head
--table_order column
--run_id 0
